"""Move kill_switch to user

Revision ID: 26e713ec4e16
Revises: 5d165fca7c0b
Create Date: 2025-05-27 12:22:56.175224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e713ec4e16'
down_revision: Union[str, None] = '5d165fca7c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker_accounts', 'kill_switch')
    op.add_column('users', sa.Column('kill_switch', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kill_switch')
    op.add_column('broker_accounts', sa.Column('kill_switch', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
