"""Add kill_switch to User

Revision ID: 5d165fca7c0b
Revises: 4dd3f9a286c3
Create Date: 2025-05-27 12:07:42.231626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d165fca7c0b'
down_revision: Union[str, None] = '4dd3f9a286c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_accounts', sa.Column('kill_switch', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker_accounts', 'kill_switch')
    # ### end Alembic commands ###
