"""Updated broker_account table with telegram_bot_token, stop_loss, target; removed defaults

Revision ID: c58510ac5044
Revises: 28eefe992ab3
Create Date: 2025-06-03 10:03:16.617437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c58510ac5044'
down_revision: Union[str, None] = '28eefe992ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_accounts', sa.Column('telegram_bot_token', sa.String(), nullable=True))
    op.add_column('broker_accounts', sa.Column('stop_loss', sa.Float(), nullable=True))
    op.add_column('broker_accounts', sa.Column('target', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker_accounts', 'target')
    op.drop_column('broker_accounts', 'stop_loss')
    op.drop_column('broker_accounts', 'telegram_bot_token')
    # ### end Alembic commands ###
